Check client for permission inconsistency
antibot-dev-team/antibot-agent pull request #11
Opened 2021-08-13 11:26 UTC by Cravtos

Насколько хорошим решением будет сделать так, как я сделал?

Кажется не особо правильным, что функции возвращают Promise. И в `sendData()` кажется, что получилось нагромождение.

2021-08-15 11:14 UTC, manmolecular requested changes
Для нашего текущего решения - нормально. Т.е., если говорить более широко, то у нас потенциально могла бы быть (в будущем, при большом количестве разношерстных проверок, синхронных и асинхронных) одна async-функция (допустим, та же `prepareRequestBody` или `collect`), которая await-ила бы различные async-проверки внутри себя, складывала их в одно тело и возвращала промис, который мы затем бы резолвили - то есть, нам не нужно было бы делать множественный `.then()` для всех, или там строить огромный чейн, мы могли бы это объединить, но сейчас нам это не нужно - у нас это фактически частный случай с navigator query.

Функции возвращают Promise, по коду всё ок - под "не особо правильно" ты имеешь в виду что? С точки зрения кода, с точки зрения архитектурной, или с какой-то ещё? Можно где-то переписать на async/await синтаксис, но это самой логики исполнения сейчас не изменит, т.е. в этом же синтаксическом сахаре будет работать тот же механизм.

С `sendData()` отписал в комментарии к функции.

Можно немного упростить, и я сделаю пере-ревью.

2021-08-15 11:14 UTC, manmolecular commented on src/properties.ts
> +      });
Можно немного проще:
```js
    return navigator.permissions.query({name: 'notifications'})
      .then(permissionStatus => Notification.permission === 'denied' && permissionStatus.state === 'prompt');
```

2021-08-15 11:14 UTC, manmolecular commented on src/properties.ts
> +      });
Второй return не нужен, т.к. мы упростили всё до стрелочного синтаксиса, а выше ты уже возвращаешь промис

2021-08-15 11:14 UTC, manmolecular commented on src/properties.ts
> +      }.bind(this));
Можно упростить с async/await, чтобы избежать нагромождения:
```js
  async collect(): Promise<ClientProperties> {
    const inconsistent_permissions = await this.checkPermissions();

    return {
      inconsistent_permissions: inconsistent_permissions,
      languages: this.getLanguages(),
      plugins: this.getPlugins(),
      custom_window: this.getWindowCustomProperties(),
      ua: this.getUserAgent(),
      webdriver: this.getWebdriver(),
      has_window_chrome: this.hasWindowChrome(),
    };
  }
```

2021-08-15 11:14 UTC, manmolecular commented on src/properties.ts
> +      }.bind(this));
И переменная `inconsistent_permissions` должна быть `inconsistentPermissions` - мы используем underscore только для общения с JSON-структурами (т.к. на бэкэнд стороне ожидаем underscore-style), а внутри кода, во всем, что не попадает в JSON напрямую делаем camelCase, стандарт для js

Т.е.
```js
return {
  inconsistent_permissions: inconsistentPermissions
...
};
```
Первое - ключ в JSON с underscore, второе - значение нашей переменной в camelCase

2021-08-15 11:14 UTC, manmolecular commented on src/agent.ts
>    }
Можно упростить:
```js
  /**
   * Prepare body with client's data
   */
  async prepareRequestBody(): Promise<AnalyzeRequest> {
    // TODO/Brainstorm: Think about request format
    //  Questions here:
    //  1. Which parameters are required to correctly detect bots? UA is enough?
    //  2. Which window.*, document.* objects we need?

    return {
      properties: await this._propertiesCollector.collect()
    };
  }
```

Я бы хотел сказать что нам эта функция (подготовки тела) вообще по сути не нужна, т.к. она у нас сейчас просто оборачивает вызов collect, но тем не менее её хотелось бы оставить как враппер для будущих проверок, т.е. для их подготовки и т.д.

Возможно, тут будет несколько await и т.д.

2021-08-15 11:14 UTC, manmolecular commented on src/agent.ts
> +        }.bind(this)));
Я бы тут последнюю `);` перенес на новую строку

2021-08-15 11:14 UTC, manmolecular commented on src/agent.ts
> +        }.bind(this)));
Саму функцию я бы оставил так, как есть у тебя. Немного объемно, но сама цепочка действий прослеживается - подготовить тело, подготовить запрос, затем отправить всё это и обработать ответ. Можно как-то разнести, но я бы сейчас не стал

2021-08-15 13:59 UTC, manmolecular commented
Ещё одно замечание - наверное, нужно проверять на consistency, а не inconsistency. Т.е. свойство должно быть не инвертировано при отправке, а отправляться как есть. Если consistent, то true, если insonsistent, то false.

2021-08-15 16:29 UTC, Cravtos commented
Исправил замечания / сделал упрощения в одном коммите: f8d6d1f

По большей части сомнения были по поводу нагромождения промисов. Выглядело не очень красиво. Но после упровщения (особенно после штук await) стало намного лучше.

2021-08-15 16:34 UTC, Cravtos commented on src/agent.ts
> +      );
Может здесь после `fetch()` тоже использовать стрелочные функции?

Вроде
```javascript
.then(options => fetch(Endpoints.analyze, options)
        .then(response => {
          return response.json();
        })
        .then(response => {
          this.handleResponse(response);
        })
      );
```

или даже

```javascript
.then(options => fetch(Endpoints.analyze, options)
        .then(async response => {
          this.handleResponse(await response.json());
        })
      );
```

Как я понял в стрелочных функциях ещё и не нужно биндить `this`.

2021-08-15 17:45 UTC, manmolecular commented on src/agent.ts
> +      );
Да, конечно. Но я бы второй вариант не стал здесь использовать - мне кажется, выглядит немного перегруженно на первый взгляд? Т.е. вызывает может быть легкий ступор в первые секунды.

Может быть вот так?
```js
      .then(options => fetch(Endpoints.analyze, options)
        .then(response => response.json())
        .then(responseBody => this.handleResponse(responseBody))
        .catch(error => console.log(error))
      );
```

В остальном на твой вкус, но поддерживаю что тут тоже надо упростить.

2021-08-15 17:48 UTC, manmolecular commented on src/agent.ts
> +      );
@Cravtos

2021-08-16 06:09 UTC, Cravtos commented on src/agent.ts
> +      );
Использовал твой вариант с однострочными функциями -- b0b3965, но без ловли ошибок.

Ещё думаю о таком упрощении:
```javascript
.then(body => ({
        method: 'POST',
        body: JSON.stringify(body),
        headers: {
          'Content-Type': 'application/json'
        }
      }))
```
вместо
```javascript
.then(body => {
        return {
          method: 'POST',
          body: JSON.stringify(body),
          headers: {
            'Content-Type': 'application/json'
          }
        };
      })
```

Что скажешь?

2021-08-16 06:56 UTC, manmolecular commented on src/agent.ts
> +      );
Поддерживаю

2021-08-16 07:18 UTC, Cravtos commented on src/agent.ts
> +      );
Готово -- 29e0786

2021-08-16 11:01 UTC, manmolecular approved these changes
LGTM

2021-08-16 12:43 UTC, merged